# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Control_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Control_1
	pod 'LocoFramework', :path => "../LocoFramework/"

  target 'Control_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Control_1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
